[package]
name = "pbj"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
colog = "1.3.0"
dirs = "5.0.1"
log = "0.4.21"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.10"
