[language]
binary = "python"
version = "3.10"
name = "python"
file_extension = "py"

[project]
dependencies = []
dev_dependencies = ["pytest"]

[project.tool]
binary = "poetry"
initializes_in_project_directory = false

[project.tool.commands]
initialize = ["new", "$PROJECT_NAME"]
add_dependency = ["add"]
add_development_dependency = ["add", "--group", "dev"]

[code.directories]
source = "$PROJECT_NAME"
test = "tests"

[[code.source]]
contents = '''
class Solution:
    pass

def main():
    print("Hello, World!")

if __name__ == '__main__':
    main()
'''
file = "main.py"
variant = "leetcode"

[[code.source]]
contents = '''
def sum(addend: int, addend_two: int) -> int:
    return addened + addend_two
'''
file = "main.py"

[[code.test]]
contents = '''
from $PROJECT_NAME import 
'''
file = "test.py"

[[config]]
contents = '''
{
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true
}
'''
file = ".vscode/settings.json"
